version: "3"
services:
  web:
    image: rishabhc32/first-app:latest
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "1313:80"
    networks:
      - webnet
networks:
  webnet: